version: '3.8'

services:
  gif-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buscador-gifs-react
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
