services:
  gif-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buscador-gifs-react
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=marvel.alonso.servidorgp.somosdelprieto.com
      - LETSENCRYPT_HOST=marvel.alonso.servidorgp.somosdelprieto.com
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
